#!/bin/bash
# a simple script to help daemonize the process
DAEMONIZE="0"
for arg in $@; do
    if [[ $arg = "-d" ]] || [[ $arg = "--daemonize" ]]; then
        DAEMONIZE="1"
    fi
done
if [[ $DAEMONIZE = "1" ]]; then
    python manage.py hx $@ &> /dev/null &
else
    python -W ignore manage.py hx $@
fi
