#!/bin/bash
# a simple script to help daemonize the process
error () {
    echo -e '\n\r\033[91mERROR: hx could not evaluate. Retry without daemonizing and with --traceback\033[0m'
    exit 1
}

DAEMONIZE="0"
LOUD="0"
for arg in $@; do
    if [[ $arg = "-d" ]] || [[ $arg = "--daemonize" ]]; then
        DAEMONIZE="1"
    fi
    if [[ $arg = "-l" ]] || [[ $arg = "--loud" ]]; then
        LOUD="1"
    fi
done
if [[ $DAEMONIZE = "1" ]]; then
    python manage.py hx $@ &> /dev/null || error
elif [[ $LOUD = "1" ]]; then
    python manage.py hx $@ || error
else
    python -W ignore manage.py hx $@ || error
fi

exit 0
